#!/bin/bash

if [ $# -ne 1 ]; then
        echo "Erreur : Nombre de paramètres erroné."
        exit 1
fi 

# Récupérer le paramètre
nom_fichier="$1"

# Vérifier si c'est un fichier ou un répertoire
if [ -d "$nom_fichier" ]; then
    echo "$nom_fichier est un fichier de type répertoire"
elif [ -f "$nom_fichier" ]; then
    # Vérifier si le fichier est exécutable
    if [ -x "$nom_fichier" ]; then
        echo "$nom_fichier est un fichier ordinaire exécutable"
    else
        echo "$nom_fichier est un fichier ordinaire"
    fi
else
    echo "Erreur : '$nom_fichier' n'existe pas ou n'est ni un fichier ni un répertoire."
    exit 2
fi



#!/bin/bash 

if [ $# -ne 1 ]; then
        echo "Erreur : Nombre de paramètres erroné."
        exit 1
fi 

nom_repertoire="$1"

if [ -e "$nom_repertoire" ]; then
        echo "Erreur : Fichier deja existant"
        exit 2
fi

if mkdir "$nom_repertoire" 2>/dev/null ; then
        echo "Le fichier de type répertoire '$nom_repertoire' à été crée."
else
        echo "Erreur : Impossible de crée le fichier de typé répertoire '$nom_repertoire'."
        exit 3 
fi



#!/bin/bash 

if [ $# -ne 2 ]; then
        echo "Erreur : Nombre de paramètres erroné."
        exit 1
fi 


recherche_mot="$1"
fichier_recherche="$2"

# Vérifier si c'est un fichier
if [ -f "$fichier_recherche" ]; then
    if grep -c "$recherche_mot" "$fichier_recherche" > /dev/null ; then
        echo "Le fichier "$fichier_recherche" contient le mot "$recherche_mot""
    else
        echo "Le fichier "$fichier_recherche" ne contient pas le mot "$recherche_mot""
fi
else
    echo "Erreur : '$fichier_recherche' n'existe pas ou n'est n'est pas un fichier ordinaire."
    exit 2
fi

#!/bin/bash 

if [ $# -ne 1 ]; then
    echo "Erreur : Un seul paramètre attendu (le mot à rechercher)."
    exit 1
fi 

recherche_mot="$1"

# Parcourir tous les fichiers du répertoire courant
for fichier in *; do
    # Vérifier si c'est un fichier ordinaire
    if [ -f "$fichier" ]; then
        if grep -q "$recherche_mot" "$fichier"; then
            echo "Le fichier \"$fichier\" contient le mot \"$recherche_mot\"."
        else
            echo "Le fichier \"$fichier\" ne contient pas le mot \"$recherche_mot\"."
        fi
    fi
done
exit 0

#!/bin/bash

if [ $# -lt 2 ]; then
    echo "Erreur : Au moins deux parametres attendus."
    exit 1
fi

recherche_mot="$1"
shift 

for fichier in "$@"; do
    if [ -f "$fichier" ]; then
        if grep -q "$recherche_mot" "$fichier"; then
            echo "Le fichier \"$fichier\" contient le mot \"$recherche_mot\"."
        else
            echo "Le fichier \"$fichier\" ne contient pas le mot \"$recherche_mot\"."
        fi
    else
        echo "Erreur : \"$fichier\" n'est pas un fichier ordinaire."
    fi
done
