SELECT cds, noms
FROM SPORT
ORDER BY noms ASC;


SELECT ndd, nomd
FROM DISCIPLINE
WHERE cds = 'JUD'
ORDER BY nomd DESC;


SELECT ndd, nomd
FROM DISCIPLINE
WHERE cds = 'ATH' AND genred = 'W'
ORDER BY NDD ASC;


SELECT nda, NCOMPLET, PAYSN
FROM ATHLETE
WHERE Cio = 'FRA' AND PAYSN != 'FRANCE'
ORDER BY NDA ASC;


SELECT NDA, NCOMPLET, GENRE, DATEN
FROM ATHLETE
WHERE cio= 'FRA'
ORDER BY DATEN ASC;


SELECT PRENOM
FROM ATHLETE
WHERE Cio='FRA' AND PRENOM LIKE 'V%'
ORDER BY PRENOM ASC;


SELECT NDA, COMPLET, GENRE, DATEN
FROM ATHLETE
WHERE VILLEN= 'TOULOUSE' AND cio=' FRA'
ORDER BY PRENOM ASC;


SELECT NDA, NCOMPLET, CIO, TAILLE, POIDS, Poids/2*TAILLE as IMC
FROM ATHLETE
WHERE TO_CHAR(DATEN, 'YYYY')= 2000 AND Poids IS NOT NULL AND Taille IS NOT NULL
ORDER BY IMC DESC;


SELECT CDS, NOMD
FROM DISCIPLINE
WHERE GENRED != 'W' AND GENRED != 'M' AND TYPED='P'
ORDER BY cds ASC;


SELECT *
FROM ATHLETE
WHERE (cio = 'FRA' OR cio = 'ESP' OR cio = 'ITA') AND TO_CHAR(DATEN, 'YYYY')=2000
ORDER BY NCOMPLET ASC;


SELECT NDA, NCOMPLET, TAILLE, CIO
FROM ATHLETE
WHERE (GENRE = 'F' AND TAILLE > 200) OR (GENRE = 'M' AND (TAILLE < 155 OR TAILLE > 210))
ORDER BY TAILLE ASC;


SELECT NDA, NCOMPLET, TO_CHAR(DATEN, 'YYYY') AS ANNEE
FROM ATHLETE
WHERE cio = 'FRA' AND (TO_CHAR(DATEN, 'YYYY') = '1980'
       OR TO_CHAR(DATEN, 'YYYY') = '1990'
       OR TO_CHAR(DATEN, 'YYYY') = '2000'
       OR TO_CHAR(DATEN, 'YYYY') = '2010')
ORDER BY ANNEE ASC;


SELECT NDA, NCOMPLET, TO_CHAR (DATEN, 'YYYY') AS ANNEE
FROM ATHLETE
WHERE cio = 'FRA' AND (TO_NUMBER(TO_CHAR(DATEN, 'YYYY')) BETWEEN 1980 AND 2010) AND TO_CHAR(DATEN, 'Y') =0
ORDER BY ANNEE ASC;


SELECT NDA, NCOMPLET, TO_CHAR (DATEN, 'YYYY') AS ANNEE
FROM ATHLETE
WHERE cio='FRA' AND TO_CHAR(DATEN, 'YYYY') IN ('1980', '1990', '2000', '2010')
ORDER BY ANNEE ASC;