SELECT B.NDA, B.NCOMPLET, B.CIO
FROM ATHLETE A, ATHLETE B
WHERE A.NCOMPLET = 'MARCHAND Leon'
  AND A.DATEN = B.DATEN
  AND B.NCOMPLET <> 'MARCHAND Leon';


  SELECT B.NDA, B.NCOMPLET, B.CIO
FROM ATHLETE A, ATHLETE B
WHERE A.NCOMPLET = 'MARCHAND Leon'
  AND A.VILLEN = B.VILLEN
  AND B.NCOMPLET <> 'MARCHAND Leon';


SELECT B.NDA, B.NCOMPLET, TO_CHAR(B.DATEN, 'DAY   DD MONTH YYYY') AS DATEN
FROM ATHLETE A, ATHLETE B
WHERE A.NCOMPLET = 'MARCHAND Leon'
  AND B.CIO = 'FRA'
  AND A.DATEN < B.DATEN
ORDER BY DATEN ASC;


SELECT A1.NDA, A1.NCOMPLET, A1.TAILLE, A1.CIO
FROM DISCIPLINE D, PRATIQUER P, ATHLETE A1, ATHLETE A2
WHERE D.CDS = 'BKB'
  AND P.NDD = D.NDD
  AND P.NDA = A1.NDA
  AND A2.NCOMPLET = 'JAMES LeBron'
  AND A1.TAILLE > A2.TAILLE
ORDER BY CIO, TAILLE ASC;


SELECT A1.NDA, A1.NCOMPLET
FROM ATHLETE A1, ATHLETE A2, PRATIQUER P1, PRATIQUER P2, DISCIPLINE D1, DISCIPLINE D2
WHERE P1.NDD = P2.NDD
  AND A1.CIO = A2.CIO
  AND A1.NCOMPLET <> 'DUPONT Antoine'
  AND A2.NCOMPLET = 'DUPONT Antoine'
  AND A2.NDA = P2.NDA
  AND P2.NDD = D2.NDD
  AND P1.NDD = D1.NDD
  AND A1.NDA = P1.NDA;


SELECT DISTINCT (A1.NDA), A1.NCOMPLET, A1.CIO
FROM ATHLETE A1, GAGNER_I G1, GAGNER_I G2
WHERE G1.NDD <> G2.NDD
  AND G1.NDA = G2.NDA
  AND A1.NDA = G1.NDA
ORDER BY CIO ASC;


SELECT DISTINCT P.CIO, P.NCOMPLET
FROM PAYS P, GAGNER_E G1, GAGNER_E G2, DISCIPLINE D1, DISCIPLINE D2, SPORT S1, SPORT S2
WHERE S1.CDS <> S2.CDS
  AND D2.CDS = S2.CDS
  AND G2.NDD = D2.NDD
  AND D1.CDS = S1.CDS
  AND G1.NDD = D1.NDD
  AND P.CIO = G2.CIO
  AND P.CIO = G1.CIO
  AND G1.MEDAILLE = 'G'
  AND G2.MEDAILLE = 'G'
ORDER BY CIO ASC;


SELECT DISTINCT (S1.NOMS), P.CIO, P.NCOMPLET
FROM PAYS P, GAGNER_E G1, GAGNER_E G2, GAGNER_E G3, DISCIPLINE D1, DISCIPLINE D2, DISCIPLINE D3, SPORT S1, SPORT S2, SPORT S3
WHERE S2.CDS = S3.CDS
  AND S1.CDS = S2.CDS
  AND S3.CDS = D3.CDS
  AND S2.CDS = D2.CDS
  AND S1.CDS = D1.CDS
  AND G3.NDD = D3.NDD
  AND G2.NDD = D2.NDD
  AND G1.NDD = D1.NDD
  AND P.CIO = G3.CIO
  AND P.CIO = G2.CIO
  AND P.CIO = G1.CIO
  AND G3.MEDAILLE = 'B'
  AND G2.MEDAILLE = 'S'
  AND G1.MEDAILLE = 'G'
ORDER BY CIO ASC;


SELECT DISTINCT (A1.NDA), A1.NCOMPLET, A1.PAYSN AS NAI
FROM ATHLETE A1
WHERE A1.PAYSN <> 'MONACO'
  AND A1.PAYSN <> 'GUADELOUPE'
  AND A1.PAYSN <> 'REUNION'
  AND A1.PAYSN <> 'MAYOTTE'
  AND A1.PAYSN <> 'MARTINIQUE'
  AND A1.PAYSN <> 'FRANCE'
  AND A1.CIO = 'FRA';


SELECT DISTINCT A.NDA, A.NCOMPLET, A.CIO
FROM ATHLETE A, PRATIQUER P1, PRATIQUER P2, DISCIPLINE D1, DISCIPLINE D2
WHERE D1.CDS <> D2.CDS
  AND P2.NDD = D2.NDD
  AND P1.NDD = D1.NDD
  AND A.NDA = P2.NDA
  AND A.NDA = P1.NDA;
