ALTER TABLE athlete
DROP CONSTRAINT fk_athlete_cio;

ALTER TABLE athlete
ADD CONSTRAINT fk_athlete_cio FOREIGN key (cio) REFERENCES PAYS(cio)
DEFERRABLE INITIALLY IMMEDIATE ;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, DEFERRABLE, DEFERRED
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'ATHLETE'
ORDER BY CONSTRAINT_TYPE ASC;

INSERT INTO Athlete (nda, ncomplet, cio)
VALUES (9999999,'TESTE Olivier', 'XXX');

DELETE FROM PAYS WHERE CIO='FRA';

UPDATE PAYS SET CIO = 'XXX' WHERE CIO = 'FRA';

UPDATE ATHLETE SET CIO = 'XXX'  WHERE NCOMPLET = 'RINER Teddy';


ALTER table athlete
MODIFY CONSTRAINT fk_athlete_cio INITIALLY DEFERRED;


INSERT INTO Athlete (nda, ncomplet, cio)
VALUES (9999999,'TESTE Olivier', 'XXX');

SELECT *
FROM ATHLETE
WHERE cio = 'XXX';

COMMIT;

