ALTER TABLE athlete
DROP CONSTRAINT fk_athlete_cio;

ALTER TABLE athlete
ADD CONSTRAINT fk_athlete_cio FOREIGN key (cio) REFERENCES PAYS(cio)
DEFERRABLE INITIALLY IMMEDIATE ;

SELECT TABLE_NAME, CONSTRAINT_NAME, CONSTRAINT_TYPE, DEFERRABLE, DEFERRED
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'ATHLETE'
ORDER BY CONSTRAINT_TYPE ASC;

INSERT INTO Athlete (nda, ncomplet, cio)
VALUES (9999999,'TESTE Olivier', 'XXX');

DELETE FROM PAYS WHERE CIO='FRA';

UPDATE PAYS SET CIO = 'XXX' WHERE CIO = 'FRA';

UPDATE ATHLETE SET CIO = 'XXX'  WHERE NCOMPLET = 'RINER Teddy';


ALTER table athlete
MODIFY CONSTRAINT fk_athlete_cio INITIALLY DEFERRED;


INSERT INTO Athlete (nda, ncomplet, cio)
VALUES (9999999,'TESTE Olivier', 'XXX');

SELECT *
FROM ATHLETE
WHERE cio = 'XXX';

INSERT INTO Athlete (nda, ncomplet, cio)
VALUES (9999999,'TESTE Olivier', 'XXX');

COMMIT;

INSERT INTO Athlete (nda, ncomplet, cio)
VALUES (9999999,'LAROUSSI Nabil', 'IUT');

INSERT INTO PAYS (cio)
VALUES ('IUT');

COMMIT;

SELECT *
FROM PAYS
WHERE cio = 'IUT';

create table TMP_PAYS(
    cio CHAR(3),
    nomp VARCHAR(30),
    nda  DECIMAL(7),
    CONSTRAINT pk_tmp_pays PRIMARY KEY (cio) DEFERRABLE INITIALLY IMMEDIATE 
    
);

create table TMP_ATHLETE(
    nda DECIMAL(7),
    ncomplet VARCHAR(50),
    cio  CHAR(3),
    CONSTRAINT pk_tmp_athlete PRIMARY KEY (nda) DEFERRABLE INITIALLY IMMEDIATE,
    CONSTRAINT fk_tmp_athlete FOREIGN KEY (cio) REFERENCES TMP_PAYS(cio) DEFERRABLE INITIALLY IMMEDIATE
);

ALTER TABLE TMP_PAYS
ADD CONSTRAINT fk_tmp_pays FOREIGN KEY (nda) REFERENCES TMP_ATHLETE(nda) DEFERRABLE INITIALLY IMMEDIATE; 

INSERT INTO TMP_ATHLETE (nda, ncomplet, cio)
VALUES (1891323,'RINER Teddy', 'FRA');


INSERT INTO TMP_PAYS (cio, nomp, nda)
VALUES ('FRA', 'France', 1891323);

ALTER table TMP_ATHLETE
MODIFY CONSTRAINT fk_tmp_athlete INITIALLY DEFERRED;

COMMIT;

SELECT *
FROM TMP_PAYS;

SELECT *
FROM TMP_ATHLETE;

ALTER TABLE TMP_ATHLETE DROP CONSTRAINT fk_tmp_athlete;
DROP TABLE TMP_PAYS;
DROP TABLE TMP_ATHLETE;

